Contact Form and Footer Section Added
Hidar37/simple-portfolio pull request #3
Opened 2022-08-23 18:41 UTC by Hidar37

- contact form have been added.
- style to contact completely added.
- footer section have been added.
- linters error have been removed.

2022-08-23 18:58 UTC, mukhammadrizooff requested changes
Hi @Hidar37, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good design ✔️ 
- Correct validations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 18:58 UTC, mukhammadrizooff commented on index.html
> +    <button type="submit" class="in_touch_btn">Get in touch</button>
- [ ] [REQUIRED] Please fix your `Get in touch button because it is not working in my case.

2022-08-24 05:46 UTC, franclobo requested changes
Hi, @Hidar37 and @zied2112, 

You are doing well! 👍🏽 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] Kindly add your partner in the authors' section on the README file. 👽 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 05:46 UTC, franclobo commented on index.html
> +      <button type="submit" class="in_touch_btn">Get in touch</button>
- [ ] Please 🙏🏽 review the function of the Submit button. I couldn't use it.
- As the last code reviewer suggested:

> [REQUIRED] Please fix your Get in touch button because it is not working in my case.

https://user-images.githubusercontent.com/58642949/186336766-1ce834bf-16b9-4071-822d-398979b467ad.mp4

2022-08-24 07:02 UTC, Hidar37 commented on index.html
> +      <button type="submit" class="in_touch_btn">Get in touch</button>
@franclobo Hello Dear sir
I thing your not using the correct version of me code I have made this changes in pervious commit and its working correct for me and for me coding partners.
in the newest commit I have added the button inside the form. but in the video you send me its showing the pervious version of my html code that is why I said if you don't mint pleas check the latest commit of mine which is : [https://github.com/Hidar37/simple-portfolio/pull/3/commits/9445e8193edeafdd1e1c288fbcfbd696fb3cb244](url).
I am sure I have fixed that error in the first review.

2022-08-24 07:12 UTC, muneebulrehman approved these changes
Hi @Hidar37 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Good design
- Good follow-up with the previous reviewer.
- Descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 07:41 UTC, merged

2022-08-24 11:31 UTC, franclobo commented on index.html
> +      <button type="submit" class="in_touch_btn">Get in touch</button>
Hello, @Hidar37 🤝 
Thanks for your comment. May you were doing changes in your branch while I was reviewing it? 🤔 It is because when I started to revise there weren't linter errors, but when I finished it, there were linter errors. In that case, I must have invalidated your pull request and don't revise until you fix the linter errors. Please, 🙏🏽 don´t do changes after submission we must wait to do it after the revision has finished. The last commit was pushed a few minutes before I finished reviewing. It is good to know that you have already approved the project now. ✌🏽